// <auto-generated />
namespace BookStoreAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class order_total : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order_total));
        
        string IMigrationMetadata.Id
        {
            get { return "201811081855443_order_total"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
